version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    cooldown:
      default-days: 30
      semver-major-days: 10
      semver-minor-days: 20
      semver-patch-days: 7
      include:  
        "*"

    schedule:
      interval: daily
